name: Ouroboros
version: 1.0.0
main: com.perceus.ouroboros.Ouroboros
description: MMO stats and functions.
authors:
    - Perceus
api-version: '1.20'
load: STARTUP
commands:
    skills:
        description: displays skills to player
        usage: /skills